Feature/hilbert cli tools
hilbert/hilbert-cli pull request #44
Opened 2016-12-12 05:59 UTC by malex984

Implement / update / fix issues mentioned by #13. Closes #13 
And started fixing issues due to #14

2016-12-12 09:48 UTC, porst17 requested changes
I enabled automated testing with TavisCI and they are still failing. I know that there are still many tests missing, but the general framework should be in place and working in principle.

2016-12-12 09:48 UTC, porst17 commented on .travis.yml
>    - source ~/.venv/bin/activate
Travis CI tests are failing on this line.

2016-12-12 14:04 UTC, malex984 commented
Seems to be fixed now

2017-02-06 00:09 UTC, malex984 commented
it seems to be enough for a release candidate now.

2017-02-06 00:11 UTC, merged